### ISSUE TITLE
Issue authenticating

### ISSUE THREAD

**Issue by eavanvalkenburg** [OpenXbox/xbox-smartglass-core-python#10]
Hi,

Suddenly I am getting an error when trying to authenticate, this happens both through the rest api as well as with xbox-authenticate and xbox-tui, this is the stacktrace:

>   File "/usr/local/lib/python3.6/dist-packages/urwid/wimp.py", line 540, in keypress
>     self._emit('click')
>   File "/usr/local/lib/python3.6/dist-packages/urwid/widget.py", line 460, in _emit
>     signals.emit_signal(self, name, self, *args)
>   File "/usr/local/lib/python3.6/dist-packages/urwid/signals.py", line 265, in emit
>     result |= self._call_callback(callback, user_arg, user_args, args)
>   File "/usr/local/lib/python3.6/dist-packages/urwid/signals.py", line 295, in _call_callback
>     return bool(callback(*args_to_pass))
>   File "/usr/local/lib/python3.6/dist-packages/xbox/webapi/scripts/tui.py", line 274, in _on_button_press
>     self._authenticate(email, pwd)
>   File "/usr/local/lib/python3.6/dist-packages/xbox/webapi/scripts/tui.py", line 252, in _authenticate
>     self.auth_mgr.authenticate(do_refresh=True)  # do_refresh=self.need_refresh
>   File "/usr/local/lib/python3.6/dist-packages/xbox/webapi/authentication/manager.py", line 174, in authenticate
>     self.access_token, self.refresh_token = self._windows_live_authenticate(self.email_address, self.password)
>   File "/usr/local/lib/python3.6/dist-packages/xbox/webapi/authentication/manager.py", line 228, in _windows_live_authenticate
>     response = self.__window_live_authenticate_request(email_address, password)
>   File "/usr/local/lib/python3.6/dist-packages/xbox/webapi/authentication/manager.py", line 391, in __window_live_authenticate_request
>     server_data = self.extract_js_object(resp.content, "ServerData")
>   File "/usr/local/lib/python3.6/dist-packages/xbox/webapi/authentication/manager.py", line 208, in extract_js_object
>     return demjson.decode(matches[0])
>   File "/usr/local/lib/python3.6/dist-packages/demjson.py", line 5699, in decode
>     return_stats=(return_stats or write_stats) )
>   File "/usr/local/lib/python3.6/dist-packages/demjson.py", line 4915, in decode
>     raise errors[0]
> demjson.JSONDecodeError: Missing value for object property, expected ":"

these are the versions:
{"xbox-smartglass-auxiliary":null,"xbox-smartglass-core":"1.0.12","xbox-smartglass-nano":null,"xbox-smartglass-rest":"0.9.8","xbox-smartglass-stump":"0.9.5","xbox-webapi":"1.1.7"}

**Comment by eavanvalkenburg** [comment]
Seems to have resolved after additional packages were updated

**Comment by tuxuser** [comment]
Interesting, normally an update to Xbox-webapi 1.1.7 should have solved it right away.
