### ISSUE TITLE
xbox-client 

### ISSUE THREAD

**Issue by carlberg74** [OpenXbox/xbox-smartglass-core-python#14]
Hi,

When running xbox-client or many of the other commands, I get this error.

# xbox-client --verbose
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.AccessToken'> from file
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.RefreshToken'> from file
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.UserToken'> from file
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.XSTSToken'> from file
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.138
<XStructObj: None>(Container: 
    header = Container: 
        pkt_type = PacketType.DiscoveryResponse
        unprotected_payload_length = 655
        protected_payload_length = None
        version = 2
    unprotected_payload = Container: 
        flags = PrimaryDeviceFlag.AllowAnonymousUsers|AllowAuthenticatedUsers
        type = ClientType.XboxOne
        name = u'Xbox-SystemOS' (total 13)
        uuid = 049ae374-d032-46b4-3f98-8c1fa887fd4c
        last_error = 0
        cert = <CertificateInfo: liveid=FD00F24E11D68BXX, pubkey=<cryptography.hazmat.backends.openssl.ec._EllipticCurvePublicKey object at 0x7fd4f88a4400>>
    protected_payload = None)
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.138
<XStructObj: None>(Container: 
    header = Container: 
        pkt_type = PacketType.DiscoveryResponse
        unprotected_payload_length = 655
        protected_payload_length = None
        version = 2
    unprotected_payload = Container: 
        flags = PrimaryDeviceFlag.AllowAnonymousUsers|AllowAuthenticatedUsers
        type = ClientType.XboxOne
        name = u'Xbox-SystemOS' (total 13)
        uuid = 049ae374-d032-46b4-3f98-8c1fa887fd4c
        last_error = 0
        cert = <CertificateInfo: liveid=FD00F24E11D68BXX, pubkey=<cryptography.hazmat.backends.openssl.ec._EllipticCurvePublicKey object at 0x7fd4f88a4128>>
    protected_payload = None)
Traceback (most recent call last):
  File "/usr/local/bin/xbox-client", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/scripts/client.py", line 76, in main
    state = console.connect(userhash, token)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/console.py", line 284, in connect
    xsts_token=xsts_token)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/protocol.py", line 452, in connect
    self.send_message(m)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/protocol.py", line 137, in send_message
    data = packer.pack(msg, self.crypto)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/packer.py", line 117, in pack
    packed_protected = crypto.encrypt(iv, packed_protected)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/crypto.py", line 274, in encrypt
    return Crypto._encrypt(self._encrypt_key, iv, plaintext)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/crypto.py", line 323, in _encrypt
    return Crypto._crypt(key=key, iv=iv, encrypt=True, data=data)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/crypto.py", line 341, in _crypt
    return cryptor.update(data) + cryptor.finalize()
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 131, in update_into
    "unsigned char *", self._backend._ffi.from_buffer(buf)
TypeError: from_buffer() cannot return the address of the raw string within a bytes or unicode or bytearray object

----
Requirement already satisfied: xbox-smartglass-core in /usr/local/lib/python3.5/dist-packages (1.0.12)
Requirement already satisfied: xbox-webapi>=1.1.2 in /usr/local/lib/python3.5/dist-packages (from xbox-smartglass-core) (1.1.7)
Requirement already satisfied: construct==2.9.41 in /usr/local/lib/python3.5/dist-packages (from xbox-smartglass-core) (2.9.41)
Requirement already satisfied: gevent==1.3.7 in /usr/local/lib/python3.5/dist-packages (from xbox-smartglass-core) (1.3.7)
Requirement already satisfied: appdirs==1.4.3 in /usr/local/lib/python3.5/dist-packages (from xbox-smartglass-core) (1.4.3)
Requirement already satisfied: urwid==2.0.1 in /usr/local/lib/python3.5/dist-packages (from xbox-smartglass-core) (2.0.1)
Requirement already satisfied: cryptography==2.3.1 in /usr/local/lib/python3.5/dist-packages (from xbox-smartglass-core) (2.3.1)
Requirement already satisfied: aenum==2.1.2; python_version <= "3.5" in /usr/local/lib/python3.5/dist-packages (from xbox-smartglass-core) (2.1.2)
Requirement already satisfied: dpkt==1.9.1 in /usr/local/lib/python3.5/dist-packages (from xbox-smartglass-core) (1.9.1)
Requirement already satisfied: demjson in /usr/local/lib/python3.5/dist-packages (from xbox-webapi>=1.1.2->xbox-smartglass-core) (2.2.4)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from xbox-webapi>=1.1.2->xbox-smartglass-core) (2.9.1)
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in /usr/local/lib/python3.5/dist-packages (from gevent==1.3.7->xbox-smartglass-core) (0.4.15)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /usr/local/lib/python3.5/dist-packages (from cryptography==2.3.1->xbox-smartglass-core) (1.12.3)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.5/dist-packages (from cryptography==2.3.1->xbox-smartglass-core) (0.24.0)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3/dist-packages (from cryptography==2.3.1->xbox-smartglass-core) (1.10.0)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python3.5/dist-packages (from cryptography==2.3.1->xbox-smartglass-core) (2.8)
Requirement already satisfied: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi!=1.11.3,>=1.7->cryptography==2.3.1->xbox-smartglass-core) (2.19)

Cant figure out why.. running python3.5.2.
Any idea?

**Comment by tuxuser** [comment]
Closed in favor of #16
