### ISSUE TITLE
Fallout 4 Xbox

### ISSUE THREAD

**Issue by unlimitedcoder2** [OpenXbox/xbox-smartglass-core-python#2]
Hello,

I came across this repo whilst searching for an api for the fallout 4 pip boy app. I was wondering if this library was capable of getting that data from my Xbox.

**Comment by tuxuser** [comment]
Hi,

Yes, it's prepared for it. I am implementing a TitleManager extension for it atm, it will proxy fallout data locally on expected port TCP 27000 - so you can use any fallout4 pipboy client in the end.

For now, checkout: https://github.com/joelday/DarkId.SmartGlass - It has wider support for TitleChannel / Auxiliary Stream data.

**Comment by unlimitedcoder2** [comment]
Thanks
