### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by recklessnl** [OpenXbox/xbox-smartglass-core-python#21]
There are 2 unofficial docker image of this available but none of them work. Would you be able to release an official Docker version? Would be very much appreciated.

**Comment by unknownskl** [comment]
Which docker images did you try and which error did you get? I see you have some activity with Home-Assistant. If you want to get this running with HA, i would suggest HunterJM's repository: https://github.com/hunterjm/hassio-addons

The docker hub account still needs to be set up, will talk with the maintainers of the project to get it up and running.

**Comment by vrnagy** [comment]
You can use github actions to do multiarch builds. They have a blog post about the setup: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by tuxuser** [comment]
@vrnagy thanks, just implemented that.

https://hub.docker.com/u/openxbox

Maybe somebody can give it a try

**Comment by vrnagy** [comment]
@tuxuser tested it in the past hour. Looks stable to me

**Comment by tuxuser** [comment]
@vrnagy thanks for the feedback. Which OS are you running?

**Comment by vrnagy** [comment]
Debian 10 with the latest docker-ce

**Comment by tuxuser** [comment]
@vrnagy thanks
Can somebody with macOS test too pls - I remember that being an issue in the past, cause its running as a "container-in-a-container" and multicast traffic is an issue with docker in general apparently..

**Comment by vrnagy** [comment]
@tuxuser Tested it on Windows Docker with WSL2 backend. Looks like it has the same multicast problem as on macOS

**Comment by tuxuser** [comment]
Yeah, multicast is a basic Docker issue apparently. Only Linux with `--network=host` seems to work with it properly.
Closing this issue for now as the current state is as close as we can get with docker..
