### ISSUE TITLE
Unable to launch apps remotely

### ISSUE THREAD

**Issue by artprzybylek** [OpenXbox/xbox-smartglass-core-python#24]
Hi,
recently I encountered issue with launching apps using ConsoleWrap.launch_title() method . I was using it earlier with "ms-windows-store:" to launch Store app and "ms-settings" for Settings. 
I observed that it stopped working for me (app does not launch on Xbox). 
I've also tried using GET request: "device/<Xbox_live_id>/launch/ms-windows-store:". The output of that was: {"launched":"ms-windows-store:","success":true} but still it didn't trigger application launch.
My suspicion is that problem is related with latest OS updates of Xbox One. 

Console is Xbox One X with OS version: 10.0.17763.4088.

I am using Python 3.7.0. This is my enviroment:
appdirs==1.4.3
asn1crypto==0.24.0
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Click==7.0
construct==2.9.41
cryptography==2.3.1
demjson==2.2.4
dpkt==1.9.1
Flask==1.0.2
gevent==1.3.7
greenlet==0.4.15
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.1
marshmallow==2.19.1
marshmallow-objects==1.0.19
pycparser==2.19
requests==2.21.0
six==1.12.0
urllib3==1.24.1
urwid==2.0.1
Werkzeug==0.15.0
xbox-smartglass-core==1.0.12
xbox-smartglass-rest==0.9.8
xbox-smartglass-stump==0.9.5
xbox-webapi==1.1.7

**Comment by tuxuser** [comment]
Closing this issue as it's not fixable on userlevel.
The functionality is removed on the daemon aka. console side.
Nothing we could possibly change.

Alexa communication is a whole other topic and not related to this project.
