### ISSUE TITLE
Xbox on different subnet

### ISSUE THREAD

**Issue by eavanvalkenburg** [OpenXbox/xbox-smartglass-core-python#27]
Hi, I noticed an earlier issue with this name, but that was resolved by adding a NIC and that is not something I want to do, I have my Xbox Smartglass Container running (as part of Home Assistant) on a machine in a management vnet (10.0.0.x) while my xbox is in my IoT vnet (10.0.2.x), I'm using Unifi gear, and have setup IGMP snooping on both networks, I've also added IGMP proxy with the Management Lan as upstream and the IoT lan as downstream. My firewall rules are to allow all traffic from Mngt to IoT, and I've added explicit rules to allow traffic to the xbox ip, and for UDP on port 5050 to the xboxip as well.

When I do a /device call or /device?addr=xboxip I get back:
`{"devices":{},"success":true}`

The xbox app on my phone works when connected to the IoT network and doesn't see the xbox when on the regular network.

Any pointers to what else I can try to get it working.

**Comment by tuxuser** [comment]
> The xbox app on my phone works when connected to the IoT network and doesn't see the xbox when on the regular network.
So you are saying that the issue exists with the official app too?
It is clearly a multicast forwarding issue in your network configuration.

Would be nice to see how to solve that on the network / traffic rules level. What's the status?

**Comment by tuxuser** [comment]
Closing for now.
When a network magician pops up with required knowledge how to masquerade the packets to look like they come from the internet network / same subnet, feel free to comment with an update.

**Comment by proffalken** [comment]
@eavanvalkenburg did you ever solve this? I'm in the same situation and trying to work it all out!

**Comment by eavanvalkenburg** [comment]
I wanted to use it with home assistant and they built a new integration that works, but never had it working before that

**Comment by proffalken** [comment]
Oh, ok, thanks. I'm working on using it with Hubitat, and the integration there relies on this part of the puzzle.

I'll keep digging and see what I can turn up.
