### ISSUE TITLE
dockerfile missing bind args

### ISSUE THREAD

**Issue by whatdaybob** [OpenXbox/xbox-smartglass-core-python#32]
When building the container it by default wont allow you to connect to the rest server as the interface is binding to 127.0.0.1. 

Changing this to the host machines IP allows connection. I would suggest allowing this as an environment arg if you can.

**Comment by tuxuser** [comment]
Could you please send a Pull Request for this? thanks

Related to #21

**Comment by tuxuser** [comment]
Actually a duplicate.
Please refer to #21
