### ISSUE TITLE
xbox-cli discover - broken?

### ISSUE THREAD

**Issue by dmike3** [OpenXbox/xbox-smartglass-core-python#34]
I'm getting the following when trying to run the discover option.

Xbox SmartGlass main client started
Traceback (most recent call last):
  File "/usr/local/bin/xbox-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/xbox/scripts/main_cli.py", line 426, in main
    discovered = cli_discover_consoles(args)
  File "/usr/local/lib/python3.6/dist-packages/xbox/scripts/main_cli.py", line 302, in cli_discover_consoles
    discovered = Console.discover(addr=args.address, timeout=1)
  File "/usr/local/lib/python3.6/dist-packages/xbox/sg/console.py", line 215, in discover
    cls.__start_cls_protocol()
  File "/usr/local/lib/python3.6/dist-packages/xbox/sg/console.py", line 134, in __start_cls_protocol
    cls.__protocol__.start()
  File "/usr/local/lib/python3.6/dist-packages/gevent/baseserver.py", line 325, in start
    self.init_socket()
  File "/usr/local/lib/python3.6/dist-packages/gevent/server.py", line 253, in init_socket
    self.socket = self.get_listener(self.address, self.family)
  File "/usr/local/lib/python3.6/dist-packages/xbox/sg/protocol.py", line 80, in get_listener
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
OSError: [Errno 22] Invalid argument

**Comment by dmike3** [comment]
Quick follow up to this. I was running under windows WSL. 

I tried on a full ubuntu install and it worked. hm...

**Comment by tuxuser** [comment]
Makes sense, WSL does not provide that deep OS integration it seems, e.g it cannot introduce such low level network interface changes. Likely done for security reasons.

**Comment by dmike3** [comment]
> Makes sense, WSL does not provide that deep OS integration it seems, e.g it cannot introduce such low level network interface changes. Likely done for security reasons.

Thanks, I assumed it was something related.

Is there anyway to specify the xbox I want to turn off when using xbox-cli ?

**Comment by tuxuser** [comment]
```
$ xbox-poweroff --help
usage: xbox-poweroff poweroff [-h] [--logfile LOGFILE] [-v] [--tokens TOKENS] [--refresh] [--interactive] [--address ADDRESS] [--liveid LIVEID]
                              [--all]

optional arguments:
  -h, --help            show this help message and exit
  --logfile LOGFILE     Path for logfile
  -v, --verbose         Set logging level ( -v: INFO, -vv: DEBUG, -vvv: DEBUG_INCL_PACKETS)
  --tokens TOKENS, -t TOKENS
                        Tokenfile to load
  --refresh, -r         Refresh xbox live tokens in provided token file
  --interactive, -i     Interactively choose console to connect to
  --address ADDRESS, -a ADDRESS
                        IP address of console
  --liveid LIVEID, -l LIVEID
                        LiveID to poweron
  --all                 Power off all consoles
```

Simplest to use is probably
```
xbox-poweroff -i
```

You can choose which discovered console to poweroff

Otherwise
```
xbox-poweroff -a 192.168.0.123
```

or

```
xbox-poweroff -l FD0342543633
```

**Comment by dmike3** [comment]
Thanks didn’t think to look there. I was looking at Xbox-cli

**Comment by dmike3** [comment]
Worked like a charm!

Thanks for your help.
