### ISSUE TITLE
Is it possible to launch apps directly?

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [OpenXbox/xbox-smartglass-core-python#36]
I've managed to authenticate, power the Xbox on, and wait until it's discoverable and connect. 

The last part of my script would be to launch the LiveTV app. The documentation is... less helpful than I might like. I know that I need to use the launch_title() method, and that it takes one positional arg and another optional (uri and location). However, it's less clear just what those should look like, and how I could determine the correct values (either programmatically, or just something to hardcode in... there's only one app I want to launch). I'm not the strongest python coder, but I perused the rest app's code and I see where it is using this method, but since the user has to supply the value to it, I still have no idea what I'm looking for. I'm not even sure if that value changes from Xbox to Xbox, or from reboot to reboot or whatever.

Is this even possible to do anymore? Another issue on the core-csharp project says Microsoft may have nuked this feature from orbit. 

If anyone's interested, this is to be run from Retropie plugged into the second HDMI port, and would allow it to bring up its own screen directly once activated.

**Comment by tuxuser** [comment]
> Is this even possible to do anymore? Another issue on the core-csharp project says Microsoft may have nuked this feature from orbit.

Unfortunately yes, thats what happened.
No way to work around it :(

**Comment by NoMoreNicksLeft** [comment]
Ugh. That's lame as hell. I don't think there's a way to get to it through button-presses alone... they'd always be different.

**Comment by dmike3** [comment]
Just to confirm, you cannot launch applications anymore?

**Comment by dept-jimkroon** [comment]
no, not possible

**Comment by foxriver76** [comment]
I've noticed, that it is again possible to launch titles via the iOS app. Any chance to get that working with this package again?
