### ISSUE TITLE
Rest API not working

### ISSUE THREAD

**Issue by dmike3** [OpenXbox/xbox-smartglass-core-python#37]
I may not be understanding, but I'm getting the following error below. Am I missing something?

The scripts from CLI work fine. Does the rest server not look at these login scripts?

{"message":"Console liveid is not alive","success":false}

**Comment by malosaa** [comment]
Hi mike3y 

u need to first be connected on the same lan as the xbox 
then go to http://<REST_SERVER_IP:PORT>/devices  and write down the id,
and it shows the connection status aswell

for connecting do this :
http://<REST_SERVER_IP:PORT>/device/"YOURCODEUJUSTWROTEDOWN"/connect

regards
