### ISSUE TITLE
Python 3.6 Requirement Necessary?

### ISSUE THREAD

**Issue by hunterjm** [OpenXbox/xbox-smartglass-core-python#4]
First off, thanks for the awesome documentation around the smartglass interface! I was looking to integrate this library into [Home Assistant](https://www.home-assistant.io), which is an open source home automation hub. Unfortunately, the project is run mostly on python 3.5, along with the base images they provide.

Is there a compatibility reason for this library to require 3.6 and not support 3.5, or was the decision mainly for extra language features (like Flag)?

If there are no technical limitations, would you be open to a PR enabling 3.5 support?

**Comment by Schamper** [comment]
Only blocking reason I found was the Flag feature. If you can find an elegant solution to that, feel free to make a PR.

**Comment by rytilahti** [comment]
I have been looking into the same thing -- one potential problem for that is the dependency on `construct`, whose API is (or at least used to be) quite fragile between updates (no API backwards compatibility guarantees), forcing its downstream libraries to pin on specific construct versions (currently pinned to 2.9.41 in homeassistant: https://github.com/home-assistant/home-assistant/blob/dev/requirements_all.txt#L214) which in turn causes troubles when used together if not in sync. Nothing that cannot be avoided in a way or another, but it's worth keeping that in mind.

**Comment by hunterjm** [comment]
@rytilahti - Thanks for the heads up about `construct`.

@Schamper - I was thinking of using `py-flags` with a `python_version<"3.6"` marker in `install_requires`.  I'm still testing it out.  Would you also be opposed to a downgraded `construct` to 2.9.41?  If you are, I could maintain a separate fork for use in Home Assistant.

**Comment by Schamper** [comment]
@hunterjm @rytilahti I'd have to check what changed between .41 and .45. If it's nothing important, I don't see why not. If it is, well, we'll see 😛

**Comment by Schamper** [comment]
Looks like a downgrade to construct .41 works: https://github.com/OpenXbox/xbox-smartglass-core-python/commit/558cb8ae495935a30653bd6575f370f1865093e1

@hunterjm is py-flags API compatible with Python 3.6 `enum.Flags`?  I came across [aenum](https://pypi.org/project/aenum/), which claims to be. Maybe that's a better option.

**Comment by hunterjm** [comment]
@Schamper - it doesn’t appear to be. Py-flags doesn’t allow Zero based flags. I’ll look at aenum! Thanks!
