### ISSUE TITLE
I can't install due to incompatible python?

### ISSUE THREAD

**Issue by mreassassin** [OpenXbox/xbox-smartglass-core-python#40]
I just upgraded to the latest python, but it seems maybe it's too new?

`pi@raspberrypi:~ $ python -V
Python 3.8.0
pi@raspberrypi:~ $ pip install xbox-smartglass-core
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting xbox-smartglass-core
  Using cached https://www.piwheels.org/simple/xbox-smartglass-core/xbox_smartglass_core-1.2.2-py2.py3-none-any.whl (84 kB)
ERROR: Package 'xbox-smartglass-core' requires a different Python: 3.5.3 not in '>=3.6'
pi@raspberrypi:~ $`

anybody know how I can successfully install this?

**Comment by tuxuser** [comment]
`ERROR: Package 'xbox-smartglass-core' requires a different Python: 3.5.3 not in '>=3.6'`

It looks like your binaries `python` and `pip` point to *different* python versions!

Please run
```
python --version
pip --version
```

**Comment by mreassassin** [comment]
pi@raspberrypi:~ $ python --version
Python 3.8.0
pi@raspberrypi:~ $ pip --version
pip 20.1.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

**Comment by ntindle** [comment]
You can fix this by running `python -m pip install xbox-smartglass-core`

**Comment by avalkowsky** [comment]
@tuxuser seems I have a similar problem or at least another installation problem.
When I do: 'pip install xbox-smartglass-core' I get:

`Collecting marshmallow>=3.0.0 (from marshmallow-objects->xbox-smartglass-core)
  ERROR: Could not find a version that satisfies the requirement marshmallow>=3.0.0 (from marshmallow-objects->xbox-smartglass-core) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.7.0, 1.0.0a0, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 2.0.0a1, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0b5, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4, 2.10.5, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.13.0, 2.13.1, 2.13.2, 2.13.3, 2.13.4, 2.13.5, 2.13.6, 2.14.0, 2.15.0, 2.15.1, 2.15.2, 2.15.3, 2.15.4, 2.15.5, 2.15.6, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.17.0, 2.18.0, 2.18.1, 2.19.0, 2.19.1, 2.19.2, 2.19.3, 2.19.4, 2.19.5, 2.20.0, 2.20.1, 2.20.2, 2.20.3, 2.20.4, 2.20.5, 2.21.0, 3.0.0a1, 3.0.0b1, 3.0.0b2, 3.0.0b3, 3.0.0b4, 3.0.0b5, 3.0.0b6, 3.0.0b7, 3.0.0b8, 3.0.0b9, 3.0.0b10, 3.0.0b11, 3.0.0b12, 3.0.0b13, 3.0.0b14, 3.0.0b15, 3.0.0b16, 3.0.0b17, 3.0.0b18, 3.0.0b19, 3.0.0b20, 3.0.0rc1, 3.0.0rc2, 3.0.0rc3, 3.0.0rc4, 3.0.0rc5)
ERROR: No matching distribution found for marshmallow>=3.0.0 (from marshmallow-objects->xbox-smartglass-core)`

my pyton/pip versions:
`python --version                                                                                                        
Python 2.7.16
 pip --version                                                                                    
pip 19.1.1 from /Library/Python/2.7/site-packages/pip-19.1.1-py2.7.egg/pip (python 2.7)`

Do you maybe have an idea what's going on and go to get through it ;)?

**Comment by rytilahti** [comment]
Looking at pypi page (https://pypi.org/project/marshmallow/), the most recent version depends on python >=3.5 and the most recent release of this project depends on python >=3.6 (https://pypi.org/project/xbox-smartglass-core/), so perjhaps python2 is not supported in the version you are trying to install?

**Comment by AnInternetTroll** [comment]
On Linux systems it's often that the default version of `python` is 2.7, so to install on python 3 use `python3 -m pip install` or just `pip3 install`

**Comment by avalkowsky** [comment]
thanks, that was it!
