### ISSUE TITLE
[UWP development] Mixing smartglass and device portal core API

### ISSUE THREAD

**Issue by avalkowsky** [OpenXbox/xbox-smartglass-core-python#41]
Hi there,

First of all, you've bee doing a terrific job with backward engineering of the smartglass protocol, no doubts about that!

I have a following question:
Have you tried to mix, use in the same time, the smartglass, for instance to start the console, and device portal core api (https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core) to for instance install/start an app using its id?

I tried but it looked like to use smartglass one has to be outside of the 'dev mode' which is at the same time required to use device portal core api.

Maybe it's only matter of some configuration. 
Do you have some experience in that field?

Thanks again,
cheers!

**Comment by mitchcapper** [comment]
@avalkowsky  smartglass works in dev mode.    You can easily see the device portal API use you use the web interface with the browser proxy in action too.
Smartglass supports starting the console, but yes for dev work this api would be used.     I think a python wrapper around the device portal API however would be beyond the scope of this project's goals.

**Comment by tuxuser** [comment]
Agree, its out of scope for this project. Here are two hints:

https://github.com/tunip3/devmodeapi
https://github.com/microsoft/WindowsDevicePortalWrapper
